// Generated by CoffeeScript 1.9.2
(function() {
  window._ = {
    findWhere: function(objs, condition) {
      var check, o;
      check = function(item) {
        var k, v;
        for (k in condition) {
          v = condition[k];
          if (item[k] !== v) {
            return false;
          }
        }
        return true;
      };
      return ((function() {
        var i, len, results;
        results = [];
        for (i = 0, len = objs.length; i < len; i++) {
          o = objs[i];
          if (check(o)) {
            results.push(o);
          }
        }
        return results;
      })())[0];
    }
  };

}).call(this);
